name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build
        run: |
          docker build . # will run buildx
